"""
🏥 Clinical Report Generator

Purpose:
    Generate human-readable clinical reports from inference results.
    Produces both plain-text and structured formats suitable for
    clinical review and record-keeping.

Key Functions:
    - generate_clinical_report(): Full report as formatted text
    - generate_report_dataframe(): Tabular report as DataFrame
    - save_clinical_report(): Save report to file

Example Usage:
    >>> summary = infer(bundle, patient_data, logger=logger)
    >>> report = generate_clinical_report(summary)
    >>> print(report)
"""

import logging
from datetime import datetime
from pathlib import Path

import pandas as pd

from src.inference.inference_engine import InferenceSummary, MultiBundleSummary


##### Report Generation #####

def generate_clinical_report(summary: InferenceSummary) -> str:
    """Generate a formatted clinical report from inference results.

    Args:
        summary: InferenceSummary from the inference engine

    Returns:
        Formatted multi-line report string
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "╔══════════════════════════════════════════════════════════════╗",
        "║              GSM CLINICAL INFERENCE REPORT                   ║",
        "╚══════════════════════════════════════════════════════════════╝",
        "",
        f"  Report Generated:  {now}",
        f"  Model Bundle:      {summary.bundle_id}",
        f"  Classifier:        {summary.model_name}",
        f"  Ensemble Strategy: {summary.ensemble_strategy}",
        f"  Training Dataset:  {summary.training_dataset or 'N/A'}",
        f"  Training Samples:  {summary.n_training_samples}",
        f"  Expected Features: {summary.n_features_expected}",
        f"  Bundle Created:    {summary.bundle_created_at or 'N/A'}",
        f"  sklearn Version:   {summary.bundle_sklearn_version or 'N/A'}",
        "",
        "  ── Summary ──",
        f"  Total Samples:     {summary.n_samples}",
        f"  Positive (disease):{summary.n_positive}",
        f"  Negative (control):{summary.n_negative}",
        f"  Mean Confidence:   {summary.mean_confidence:.2%}",
        "",
        "═" * 62,
        "  INDIVIDUAL PATIENT RESULTS",
        "═" * 62,
    ]

    for r in summary.results:
        risk_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(
            r.risk_level, "⚪"
        )

        lines.extend([
            "",
            f"  ┌─ Sample: {r.sample_id}",
            f"  │  Prediction:   {r.predicted_label}",
            f"  │  Confidence:   {r.confidence:.2%}",
            f"  │  Risk Level:   {risk_emoji} {r.risk_level}",
            f"  │  Model Agreement: {r.agreement_ratio:.0%} ({_agreement_text(r.agreement_ratio)})",
        ])

        if r.top_contributing_genes:
            lines.append("  │  Top Contributing Genes:")
            for gene, importance in list(r.top_contributing_genes.items())[:5]:
                bar = "█" * int(importance * 50)
                lines.append(f"  │    {gene:12s} {importance:.4f} {bar}")

        lines.append("  └" + "─" * 40)

    # Disclaimer
    lines.extend([
        "",
        "═" * 62,
        "  CLINICAL USE NOTES",
        "═" * 62,
        "  1) Prefer bundles trained on a disease cohort matching the",
        "     current patient context (e.g., prostate bundle for prostate cases).",
        "  2) If no disease-matched bundle exists, treat predictions as",
        "     exploratory and require external clinical corroboration.",
        "  3) Escalate caution when confidence < 55% or model agreement < 70%.",
        "  4) Use multi-bundle consensus only as a secondary signal, not",
        "     a replacement for disease-specific validation.",
        "",
        "═" * 62,
        "  ⚠️  DISCLAIMER",
        "═" * 62,
        "  This report is generated by an automated machine learning",
        "  pipeline for RESEARCH PURPOSES ONLY. It is NOT a medical",
        "  diagnosis. Clinical decisions should be made by qualified",
        "  healthcare professionals using this as supplementary",
        "  information alongside other diagnostic tools.",
        "═" * 62,
    ])

    return "\n".join(lines)


def _agreement_text(ratio: float) -> str:
    """Human-readable text for model agreement ratio."""
    if ratio >= 0.9:
        return "strong consensus"
    elif ratio >= 0.7:
        return "moderate consensus"
    elif ratio >= 0.5:
        return "weak consensus"
    else:
        return "split / uncertain"


def generate_report_dataframe(summary: InferenceSummary) -> pd.DataFrame:
    """Convert inference results to a DataFrame for easy export.

    Args:
        summary: InferenceSummary from the inference engine

    Returns:
        DataFrame with one row per patient sample
    """
    rows = []
    for r in summary.results:
        rows.append({
            "Sample_ID": r.sample_id,
            "Predicted_Class": r.predicted_class,
            "Predicted_Label": r.predicted_label,
            "Confidence": r.confidence,
            "Risk_Level": r.risk_level,
            "Model_Agreement": r.agreement_ratio,
            "N_Models_Positive": sum(
                1 for p in r.individual_probabilities if p >= 0.5
            ),
            "N_Models_Total": len(r.individual_probabilities),
            "Mean_Probability": (
                sum(r.individual_probabilities) / len(r.individual_probabilities)
                if r.individual_probabilities
                else 0.0
            ),
        })
    return pd.DataFrame(rows)


def save_clinical_report(
    summary: InferenceSummary,
    output_dir: Path,
    logger: logging.Logger,
) -> Path:
    """Save the clinical report to both text and Excel files.

    Args:
        summary: InferenceSummary from the inference engine
        output_dir: Directory to save the report
        logger: Logger instance

    Returns:
        Path to the text report file
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Save text report
    report_text = generate_clinical_report(summary)
    text_path = output_dir / f"clinical_report_{timestamp}.txt"
    text_path.write_text(report_text, encoding="utf-8")
    logger.info(f"📄 Clinical report saved: {text_path.name}")

    # Save Excel report
    df = generate_report_dataframe(summary)
    excel_path = output_dir / f"clinical_report_{timestamp}.xlsx"
    df.to_excel(excel_path, index=False, sheet_name="Predictions")
    logger.info(f"📊 Excel report saved: {excel_path.name}")

    return text_path


##### Multi-Bundle Report #####

def generate_multi_bundle_report(summary: MultiBundleSummary) -> str:
    """Generate a formatted clinical report for multi-bundle inference.

    Args:
        summary: MultiBundleSummary from multi_infer()

    Returns:
        Formatted multi-line report string
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "╔══════════════════════════════════════════════════════════════╗",
        "║        GSM MULTI-BUNDLE CLINICAL INFERENCE REPORT           ║",
        "╚══════════════════════════════════════════════════════════════╝",
        "",
        f"  Report Generated:  {now}",
        f"  Bundles Used:      {summary.n_bundles}",
    ]
    for bid in summary.bundle_ids:
        lines.append(f"    • {bid}")
    lines.extend([
        "",
        "  ── Summary ──",
        f"  Total Samples:     {summary.n_samples}",
        f"  Positive (disease):{summary.n_positive}",
        f"  Negative (control):{summary.n_negative}",
        f"  Mean Confidence:   {summary.mean_confidence:.2%}",
        "",
        "═" * 62,
        "  INDIVIDUAL PATIENT RESULTS",
        "═" * 62,
    ])

    for r in summary.results:
        risk_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(
            r.risk_level, "⚪"
        )
        lines.extend([
            "",
            f"  ┌─ Sample: {r.sample_id}",
            f"  │  Consensus:     {r.predicted_class}",
            f"  │  Confidence:    {r.consensus_confidence:.2%}",
            f"  │  Risk Level:    {risk_emoji} {r.risk_level}",
            f"  │  Bundle Votes:  {r.n_bundles_positive}/{r.n_bundles_total} positive",
            f"  │  Agreement:     {r.agreement_ratio:.0%} ({_agreement_text(r.agreement_ratio)})",
        ])

        # Per-bundle breakdown
        lines.append("  │  Per-Bundle Predictions:")
        for bid, pred in r.bundle_predictions.items():
            lines.append(
                f"  │    {bid}: {pred.predicted_class} "
                f"(conf={pred.confidence:.2%}, risk={pred.risk_level})"
            )

        if r.top_contributing_genes:
            lines.append("  │  Top Contributing Genes (merged):")
            for gene, importance in list(r.top_contributing_genes.items())[:5]:
                bar = "█" * int(importance * 50)
                lines.append(f"  │    {gene:12s} {importance:.4f} {bar}")

        lines.append("  └" + "─" * 40)

    lines.extend([
        "",
        "═" * 62,
        "  CLINICAL USE NOTES",
        "═" * 62,
        "  1) Prefer disease-matched bundles in the consensus set.",
        "  2) If bundle votes conflict, treat output as uncertain and",
        "     prioritize disease-specific confirmatory testing.",
        "  3) Multi-bundle consensus is best used for triage/research support,",
        "     not as a standalone diagnostic decision.",
        "",
        "═" * 62,
        "  ⚠️  DISCLAIMER",
        "═" * 62,
        "  This report is generated by an automated machine learning",
        "  pipeline for RESEARCH PURPOSES ONLY. It is NOT a medical",
        "  diagnosis. Clinical decisions should be made by qualified",
        "  healthcare professionals using this as supplementary",
        "  information alongside other diagnostic tools.",
        "═" * 62,
    ])

    return "\n".join(lines)


def generate_multi_bundle_dataframe(
    summary: MultiBundleSummary,
) -> pd.DataFrame:
    """Convert multi-bundle results to a DataFrame for export.

    Args:
        summary: MultiBundleSummary from multi_infer()

    Returns:
        DataFrame with one row per patient sample
    """
    rows = []
    for r in summary.results:
        row = {
            "Sample_ID": r.sample_id,
            "Consensus_Class": r.predicted_class,
            "Consensus_Confidence": r.consensus_confidence,
            "Risk_Level": r.risk_level,
            "Bundles_Positive": r.n_bundles_positive,
            "Bundles_Total": r.n_bundles_total,
            "Bundle_Agreement": r.agreement_ratio,
        }
        # Add per-bundle prediction columns
        for bid, pred in r.bundle_predictions.items():
            short_bid = bid.split("_")[1] if "_" in bid else bid
            row[f"{short_bid}_class"] = pred.predicted_class
            row[f"{short_bid}_conf"] = pred.confidence
        rows.append(row)
    return pd.DataFrame(rows)


def save_multi_bundle_report(
    summary: MultiBundleSummary,
    output_dir: Path,
    logger: logging.Logger,
) -> Path:
    """Save a multi-bundle clinical report to text and Excel.

    Args:
        summary: MultiBundleSummary from multi_infer()
        output_dir: Directory to save the report
        logger: Logger instance

    Returns:
        Path to the text report file
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Save text report
    report_text = generate_multi_bundle_report(summary)
    text_path = output_dir / f"multi_bundle_report_{timestamp}.txt"
    text_path.write_text(report_text, encoding="utf-8")
    logger.info(f"📄 Multi-bundle report saved: {text_path.name}")

    # Save Excel report
    df = generate_multi_bundle_dataframe(summary)
    excel_path = output_dir / f"multi_bundle_report_{timestamp}.xlsx"
    df.to_excel(excel_path, index=False, sheet_name="Consensus")
    logger.info(f"📊 Multi-bundle Excel saved: {excel_path.name}")

    return text_path
