#!/usr/bin/env python3
"""Generates the unified semantic directory and AST architectural map."""
import os
import ast

def get_module_docstring(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        tree = ast.parse(content)
        doc = ast.get_docstring(tree)
        if doc:
            return doc.strip().split('\n')[0]
    except Exception:
        pass
    return ""

def parse_ast_definitions(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        tree = ast.parse(content)
    except Exception:
        return None

    classes = []
    functions = []
    
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            methods = [n.name for n in node.body if isinstance(n, ast.FunctionDef)]
            classes.append({"name": node.name, "methods": methods})
        elif isinstance(node, ast.FunctionDef):
            functions.append(node.name)
            
    if not classes and not functions:
        return None
        
    return {"classes": classes, "functions": functions}

def generate_tree_and_ast(startpath):
    shallow_dirs = {
        'ARCHIVE': 'Consolidated legacy scripts, manuscripts, and reports',
        'data': 'Datasets and grouping files',
        'models': 'Pre-trained models and serialized bundles',
        'output': 'Auto-generated results and logs',
        'assets': 'Images and repository assets',
        'example_outputs': 'Example outputs for demonstration'
    }
    
    ignore_dirs = {'.git', 'venv', '__pycache__', '.pytest_cache', 'node_modules', '.agents', '.ai_context', '.github'}
    allowed_exts = {'.py', '.md', '.ini', '.yml', '.yaml'}
    
    folder_desc = {
        'src': 'Core Domain Logic and Pipeline',
        'scripts': 'Experiment runners and maintenance scripts',
        'tests': 'Automated test suite',
        'DOCS': 'Additional documentation'
    }
    
    tree_lines = []
    ast_lines = []
    
    for root, dirs, files in os.walk(startpath):
        dirs.sort()
        rel_root = os.path.relpath(root, startpath)
        if rel_root == '.':
            rel_root = ''
            
        new_dirs = []
        for d in dirs:
            if d in ignore_dirs or d.startswith('.'):
                continue
            if rel_root == '' and d in shallow_dirs:
                tree_lines.append(f"├── {d}/ ({shallow_dirs[d]})")
            else:
                new_dirs.append(d)
        
        dirs[:] = new_dirs
        if rel_root == '':
            continue
            
        level = rel_root.count(os.sep) + 1
        indent = '│   ' * (level - 1) + '├── '
        basename = os.path.basename(root)
        
        desc = ""
        if level == 1 and basename in folder_desc:
            desc = f" ({folder_desc[basename]})"
            
        tree_lines.append(f"{indent}{basename}/{desc}")
        
        sub_indent = '│   ' * level + '├── '
        for f in sorted(files):
            if f.startswith('.'):
                continue
            _, ext = os.path.splitext(f)
            if ext not in allowed_exts and f not in ('requirements.txt', 'dependencies.txt'):
                continue
                
            filepath = os.path.join(root, f)
            desc_str = ""
            if f.endswith('.py'):
                doc = get_module_docstring(filepath)
                if doc:
                    desc_str = f" ({doc})"
                else:
                    desc_str = " (No module docstring provided)"
                    
                # Parse AST
                parsed = parse_ast_definitions(filepath)
                if parsed:
                    rel_path = os.path.relpath(filepath, startpath)
                    ast_lines.append(f"### {rel_path}")
                    for cls in parsed['classes']:
                        ast_lines.append(f"class {cls['name']}:")
                        for m in cls['methods']:
                            ast_lines.append(f"    def {m}()")
                    for fn in parsed['functions']:
                        ast_lines.append(f"def {fn}()")
                    ast_lines.append("")
                    
            tree_lines.append(f"{sub_indent}{f}{desc_str}")

    return "\n".join(tree_lines), "\n".join(ast_lines)

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    map_path = os.path.join(root_dir, '.ai_context', 'PROJECT_MAP.md')
    
    tree_content, ast_content = generate_tree_and_ast(root_dir)
    
    new_content = f"""# Project Architecture & Semantic Map

This file is automatically generated and updated by `scripts/generate_architecture_map.py`.
It combines a high-level directory tree with a detailed Abstract Syntax Tree (AST) breakdown of all Python classes and functions.

## 1. Directory Tree
```text
.
{tree_content}
```

## 2. AST Module Definitions
{ast_content}
"""
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print("Project architecture map generated successfully.")

if __name__ == "__main__":
    main()
